name: Build and Test EventCounter

# This workflow is triggered on pushes to master, dev and feature branches
on:
    push:
        branches:
            - main
            - dev
            - feature/*
jobs:
    test:
        name: Test
        runs-on: macos-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Bundle Install
              run: bundle install

            - name: Unit tests
              run: bundle exec fastlane tests
                   