name: CI Danger
on:
  pull_request:
    branches:
      - main
      - dev
      - feature/*
jobs:
  build:
    runs-on: macos-latest
    name: "Run Danger"
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: danger/swift@3.3.0
        with:
            args: --failOnErrors --no-publish-check
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.CI_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}